name: viterium_wallet
description: Viterium - a Non-Custodial Wallet for Vite Blockchain.
publish_to: "none"

version: 1.0.0+0

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_secure_storage: 5.0.2
  shared_preferences: 2.0.15
  web_socket_channel: 2.2.0
  package_info_plus: 1.4.2
  device_info: 2.0.3
  json_annotation: 4.5.0
  intl: 0.17.0
  decimal: 2.2.0
  logger: 1.1.0
  #hive: ^2.0.4
  hive_flutter: 1.1.0
  #stash_hive: ^4.0.0
  path_provider: 2.0.10
  local_auth: 1.1.11
  #flutter_svg: 1.0.3
  qr_flutter: 4.0.0
  qr_code_scanner: 0.7.0
  share_plus: 4.0.4
  file_picker: 4.5.1
  #uni_links: 0.5.1
  http: 0.13.4
  flutter_vibrate: 1.3.0
  flutter_slidable: 0.6.0
  validators: 3.0.0
  auto_size_text: 3.0.0
  url_launcher: 6.0.20
  devicelocale: 0.5.1
  flutter_riverpod: 1.0.3
  hooks_riverpod: 1.0.3
  flutter_hooks: 0.18.3
  freezed_annotation: 1.1.0
  json_converter: 2.0.0
  fast_immutable_collections: 7.3.1
  extended_image: 6.0.1
  #go_router: ^3.0.4
  vite: 0.1.1
  #google_fonts: ^2.3.2
  cupertino_icons: ^1.0.4
  oktoast: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.1.10
  json_serializable: 6.2.0
  flutter_lints: 1.0.4
  freezed: 1.1.1
  flutter_launcher_icons: 0.9.2

# FIXME
dependency_overrides:
  vite:
    git:
      url: https://github.com/viterium/vite_dart.git
      ref: 56b229891897f00be03d563a2a7c5756e7cb4032

# Flutter launcher icons
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/icon/icon_android.png"
  image_path_ios: "assets/icon/icon.png"

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
          weight: 600
        - asset: fonts/NunitoSans-ExtraLight.ttf
          weight: 100
        - asset: fonts/NunitoSans-Light.ttf
          weight: 200
        - asset: fonts/NunitoSans-SemiBold.ttf
          weight: 700
        - asset: fonts/NunitoSans-Bold.ttf
          weight: 800
        - asset: fonts/NunitoSans-ExtraBold.ttf
          weight: 900
    - family: OverpassMono
      fonts:
        - asset: fonts/OverpassMono-Regular.ttf
          weight: 600
        - asset: fonts/OverpassMono-Light.ttf
          weight: 100
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
          weight: 500
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: fonts/Comfortaa-Light.ttf
          weight: 300
  assets:
    - assets/token_icons/
    - assets/

  uses-material-design: true

scripts:
  codegen: flutter pub run build_runner build --delete-conflicting-outputs
