name: viterium_wallet
description: Viterium - a Non-Custodial Wallet for Vite Blockchain.
publish_to: "none"

version: 1.3.0+10

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_secure_storage: 6.0.0
  shared_preferences: 2.0.15
  web_socket_channel: 2.2.0
  package_info_plus: 3.0.1
  device_info_plus: 8.0.0
  json_annotation: 4.7.0
  intl: 0.17.0
  decimal: 2.3.0
  rational: 2.2.0
  logger: 1.1.0
  #hive: ^2.0.4
  hive_flutter: 1.1.0
  #stash_hive: ^4.0.0
  path_provider: 2.0.11
  local_auth: 2.1.2
  #flutter_svg: 1.0.3
  qr_flutter: 4.0.0
  qr_code_scanner: 1.0.1
  share_plus: 6.0.1
  file_picker: 5.2.2
  #uni_links: 0.5.1
  http: 0.13.5
  flutter_vibrate: 1.3.0
  flutter_slidable: 0.6.0
  validators: 3.0.0
  auto_size_text: 3.0.0
  url_launcher: 6.1.6
  devicelocale: 0.5.5
  flutter_riverpod: 1.0.4
  hooks_riverpod: 1.0.4
  flutter_hooks: 0.18.5+1
  freezed_annotation: 2.2.0
  json_converter: 2.0.0
  fast_immutable_collections: 7.4.3
  extended_image: 6.3.1
  #go_router: ^3.0.4
  vite: 0.3.1
  viteconnect: 0.0.2
  #google_fonts: ^2.3.2
  cupertino_icons: 1.0.5
  oktoast: 3.3.1
  automatic_animated_list: 1.1.0
  lazy_load_scrollview: 1.3.0
  image_picker: 0.8.6
  #image_picker_for_web: 2.1.8
  #flutter_zxing: 0.4.0
  barcode_finder: 0.0.5
  flutter_displaymode: 0.4.0
  push: 0.1.3
  crypton: 2.0.5
  #rate_limiter: 0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.3.2
  json_serializable: 6.5.3
  flutter_lints: 2.0.1
  freezed: 2.2.0
  flutter_launcher_icons: 0.10.0

# Flutter launcher icons
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/icon/icon_android.png"
  image_path_ios: "assets/icon/icon.png"

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
          weight: 600
        - asset: fonts/NunitoSans-ExtraLight.ttf
          weight: 100
        - asset: fonts/NunitoSans-Light.ttf
          weight: 200
        - asset: fonts/NunitoSans-SemiBold.ttf
          weight: 700
        - asset: fonts/NunitoSans-Bold.ttf
          weight: 800
        - asset: fonts/NunitoSans-ExtraBold.ttf
          weight: 900
    - family: OverpassMono
      fonts:
        - asset: fonts/OverpassMono-Regular.ttf
          weight: 600
        - asset: fonts/OverpassMono-Light.ttf
          weight: 100
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
          weight: 500
    - family: AppIconsCustom
      fonts:
        - asset: fonts/AppIconsCustom.ttf
          weight: 500
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: fonts/Comfortaa-Light.ttf
          weight: 300
  assets:
    - assets/token_icons/
    - assets/

  uses-material-design: true

scripts:
  codegen: flutter pub run build_runner build --delete-conflicting-outputs
